services:
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "3000:3000"
    environment:
      - DB_PATH=sqlite.db
    volumes:
      - db_data:/usr/src/app
    networks:
      - backend-frontend-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - "8081:8081"
    environment:
      - EXPO_PUBLIC_API_URL=http://backend_service:3000
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./frontend:/usr/src/front
    stdin_open: true
    tty: true
    networks:
      - backend-frontend-network

volumes:
  db_data:

networks:
  backend-frontend-network:
    driver: bridge
