services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - db_data:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_PATH=sqlite.db

volumes:
  db_data:
